"""empty message

Revision ID: 4c7ff4120d58
Revises: 30d3b9e2051a
Create Date: 2022-06-24 09:57:41.765013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c7ff4120d58'
down_revision = '30d3b9e2051a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('population', sa.String(length=250), nullable=True),
    sa.Column('terrain', sa.String(length=250), nullable=False),
    sa.Column('climate', sa.Integer(), nullable=True),
    sa.Column('orbitalPeriod', sa.Integer(), nullable=True),
    sa.Column('rotationPeriod', sa.Integer(), nullable=True),
    sa.Column('diameter', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planets')
    # ### end Alembic commands ###
